### ISSUE TITLE
.net core / c#

### ISSUE THREAD

**Issue by mika76** [microsoft/IoT-For-Beginners#189]
Just wondering, can't you run .net core on rpi? Why not use that instead of python?

**Comment by jimbobbennett** [comment]
You can, but Python is better for IoT IMHO on a Pi.

* More students learn Python either at high school, or at Uni, or via self guided learning as most of the Pi learning is for Python. This means the learning curve for IoT is just IoT, not a programming language.
* There are much better ecosystems for hardware using Python. For example, the Seeed grove kit has Python libraries, but not .NET libraries
* Python is installed out of the box, so there is no extra steps to configure .NET core
* There are a lot more examples of Python on Pi, and a lot better documentation for folks to refer to

**Comment by mika76** [comment]
I guess all those are true, but it also perpetuates the problem. Everything is python so let's just use python does not extend the eco-system at all. 

Considering this project is Microsoft owned, why not push .net core a little? It works and a little push might actually be all that is needed. Even if as an alternative...

**Comment by jimbobbennett** [comment]
I fail to see this as a problem. Python is a great language, and there is absolutely no problem in using it. Microsoft supports many languages on many platforms, including Python.

This is open source and MIT licensed, so if you want to fork it and port to .NET core then be my guest!

**Comment by mika76** [comment]
Python is a fine language, but why limit this to it? It's for teaching so why not teach some .net too? 

Also what's with the "so if you want to fork it and port to .NET core" comment and closing this issue? It's like a slightly nicer way of telling me to f-off and that this is not a discussion worth having. I would have made it a discussion if discussions were turned on on the repo but an issue was all that was available.

I have nothing against python, but everybody and their grandmother uses python for learning IOT. But it's also like gatekeeping. Why not break the mould? You couldn't use .net easily before but now you can, so why not promote it a bit. Even if just doing one or two of the tutorials in it to show it's available and possible.

When I saw that Microsoft had created a whole series of tutorials for IOT I got excited that finally some .net love would be had in the space but was disappointed that it's still not, and I can guarantee you that I'm not the only one.

**Comment by jimbobbennett** [comment]
The "if you want to fork it comment" was not meant as a 'f-off', it was highlighting that this curriculum is free and open source, so if anyone wants to port it to a different IoT ecosystem they are more than welcome to, that was part of the reason for making it MIT licensed. I'm sorry if you feel that it came across that way, that was never the intent.

The issue was closed because we are not going to add any .NET content. We support Arduino/C++ and Raspberry Pi/Python. This is not gatekeeping, it is using the most popular tools for the job. Adding one or two lessons with a different programing language would be incredibly detrimental as students would have to then learn an entire new ecosystem for one lesson, and let's be honest most just wouldn't.

I'm sure there are many folks who want IoT content using .NET core which is why the .NET team have an entire section devoted to it: https://dotnet.microsoft.com/apps/iot. It's just not something we are going to include here.
