### ISSUE TITLE
 Please stop accepting machine translated articles

### ISSUE THREAD

**Issue by NeroBlackstone** [microsoft/IoT-For-Beginners#214]
This is a amazing project, I like it very much ~ 

As a native Chinses speaker, I check some Chinese translation and I think it is meaningless.

Bad machine translation is not only unreadable, but also increases the burden on those who really want to translate these articles.

I recommend adding "Don't use machine translation" to the translation guidelines.

**Comment by Pandz18** [comment]
Hi, 

As you're a native speaker, do please correct any mistakes that you find in the translations as it would help make it easier to understand.

I also do agree that the rule against machine translation should be placed in the translation guidelines !

Have a great day, cheers !

**Comment by NeroBlackstone** [comment]
> Hi,
> 
> As you're a native speaker, do please correct any mistakes that you find in the translations as it would help make it easier to understand.
> 
> I also do agree that the rule against machine translation should be placed in the translation guidelines !
> 
> Have a great day, cheers !

Oh, Thank you for understanding!

**Comment by Mireille-T** [comment]
Hello, thank you very much for your contribution, and sorry for the mistakes in earlier translations! They aren't machine-translated, but since Chinese is my second language and not my first (though I did study it officially), my phrasings may be awkward and I'm learning from this experience as well.

I agree that poor translations are bad and should be avoided, so I'm trying to improve my translations as well so that they are as readable as possible. Thank you for your understanding and apologies once again!

**Comment by jimbobbennett** [comment]
Thanks all for your understanding here. I'll close this issue and appreciate you all working together on the translations in the relevant issues and PRs.
