### ISSUE TITLE
Unclear instructions in lesson 4

### ISSUE THREAD

**Issue by ptoonen** [microsoft/IoT-For-Beginners#269]
Hi,

first of all: awesome project! I plan to run through this with a bunch of students starting the new school year (September). I figured I'd run through it myself first though.

In lesson 4 it becomes rather unclear what's to be [expected](https://github.com/microsoft/IoT-For-Beginners/blob/main/1-getting-started/lessons/4-connect-internet/README.md#install-python-and-vs-code
) when it comes to installing the virtualenv. It says to 'skip this step' when you're running on a rPi locally - which we will be. 

Either it's missing instructions on what to do on a rPI or it's missing instructions that you'll be required to install ```python3-venv``` on the device.

My suggestion would be to skip this step altogether on the rPI and simply include instructions on how to open a second terminal window.

Please let me know your thought and I'd be happy to submit a PR with the changes.

Cheers,

Peter

**Comment by jimbobbennett** [comment]
Hey @ptoonen - this is great to hear. Let me know if there is any way I can help support you with your students.

When running on the Pi there is no need to set up a virtual environment. The Grove install script installs pip packages globally, so rather than add the complexity of a virtual environment and having to re-install the grove packages into the virtual environment, I felt it was easier to just not use a virtual environment for the Pi. I know a lot of developers are not too worried if their systems have lots of global packages installed as they usually just re-flash the SD card for each new project.

How do you think this can be made clearer? Should I expand the 'skip this step' instructions to include an explanation that virtual environments wont't be used on the Pi?

**Comment by ptoonen** [comment]
Hey Jim, my suggestion would be to indeed provide some more clarity that the entire virtual environment section - rather than just 'this step' - can be skipped and add some instructions how to open a second (terminal) window. I think it would save me a lot of questions ;-)

**Comment by jimbobbennett** [comment]
I've added a bit more details, but would love a PR with more improvements that would help clarity!

**Comment by jlooper** [comment]
@ptoonen are we ok to close this issue? Did Jim's changes work for you?

**Comment by ptoonen** [comment]
Hey @jlooper I haven't got around to checking the full changes yet, I'll try to to that today/tomorrow and will update this issue accordingly :)

**Comment by ptoonen** [comment]
Yup, looking good @jimbobbennett, thanks!
