### ISSUE TITLE
Error running code for pi nightlight sensor

### ISSUE THREAD

**Issue by marty-optum** [microsoft/IoT-For-Beginners#299]
Hello,

I followed the directions in [Build a nightlight - Raspberry Pi](https://github.com/microsoft/IoT-For-Beginners/blob/main/1-getting-started/lessons/3-sensors-and-actuators/pi-sensor.md) for the light sensor.

When I run `python3 app.py` from within the VS Code terminal, I get the following message: 

> Check whether I2C enabled and   Grove Base Hat RPi  or  Grove Base Hat RPi Zero  inserted

I checked the code, and it seems ok.  Here is a picture of my Pi setup with the Grove hat, Grove Light sensor, and each of the packages they came in from Seeed.

![IMG_6776](https://user-images.githubusercontent.com/71525323/131606220-85ad1051-86ef-4b2c-9ca2-9fbeba362cb8.jpg)

Any suggestions to determine what might be wrong?

Thank you.

**Comment by jimbobbennett** [comment]
Hi @marty-optum. Due to chip shortages, I've heard that Seeed have changed the chip in the base hat, so you need to make a code change to one of their libraries. I'm waiting on a new hat myself to test this out and update the instructions.

There is a thread on the Seeed forums about this:

https://forum.seeedstudio.com/t/problems-running-modules-on-a-grove-raspberry-pi-hat/259377/8

Issue #287 was also raised for this same error, so I'm going to close this issue as a duplicate, and add more details to the other issue.

**Comment by marty-optum** [comment]
Thank you, @jimbobbennett  💯
